### ISSUE TITLE
Inconsistency in tracking evaluation

### ISSUE THREAD

**Issue by 20chase** [JRDB-dataset/jrdb_toolkit#2]
Hi  @JRDB-dataset developers, 

Thanks for your great contributions. 

We are evaluating our 3D tracking algorithm in JRDB datasets with the provided toolkit. However, we found some inconsistency code in tracking_eval. In our understanding, the toolkit first convert the ground truth json file to KITTI format txt file by `convert_dataset_to_KITTI_tracking.py`. Then, we can use `run_jrdb_3d.py` to evaluate our results with the generated ground truth txt file. However, there are inconsistency definitions of the 3D bounding box. 

Specifically,  in [convert_dataset_to_KITTI_tracking.py](https://github.com/JRDB-dataset/jrdb_toolkit/blob/38f6f32170a601c32a6347eded232fba11307ddb/tracking_eval/convert_dataset_to_KITTI_tracking.py#L726) line 726-732, the 3d bounding box is defined as `h, l, w, x, y, z, rotation_y`, but in [_base_dataset.py](https://github.com/JRDB-dataset/jrdb_toolkit/blob/38f6f32170a601c32a6347eded232fba11307ddb/tracking_eval/TrackEval/trackeval/datasets/_base_dataset.py#L425) line 425 and 452, the 3d bounding box is defined as `x, y, z, l, h, w, theta`. The bounding box position and scale are totally "reversed". 

For common testing, we can unify the definition by ourselves, but what definition shall we use for the online submission.  

Looking forward to your feedback. Thanks in advance.

**Comment by JRDB-dataset** [comment]
Dear 20Chase,
Thank you for your feedback, we're sorry for the confusion, let us make
things clear.
In convert_dataset_to_KITTI_tracking.py
<https://signal3domain.com/click?redirect=https%3A%2F%2Fgithub.com%2FJRDB-dataset%2Fjrdb_toolkit%2Fblob%2F38f6f32170a601c32a6347eded232fba11307ddb%2Ftracking_eval%2Fconvert_dataset_to_KITTI_tracking.py%23L726&dID=1657009437669&linkName=convert_dataset_to_KITTI_tracking.py>
line
726-732, these lines are used to read the box predictions, which assumed
the predictions are already in KITTI format
<https://signal3domain.com/click?redirect=https%3A%2F%2Fgithub.com%2Fbostondiditeam%2Fkitti%2Fblob%2Fmaster%2Fresources%2Fdevkit_object%2Freadme.txt&dID=1657009437669&linkName=KITTI
format> (h, w, l, x, y, z, r - in KITTI camera coordinate system).
Also, Before reaching _base_dataset.py
<https://signal3domain.com/click?redirect=https%3A%2F%2Fgithub.com%2FJRDB-dataset%2Fjrdb_toolkit%2Fblob%2F38f6f32170a601c32a6347eded232fba11307ddb%2Ftracking_eval%2FTrackEval%2Ftrackeval%2Fdatasets%2F_base_dataset.py%23L425&dID=1657009437669&linkName=_base_dataset.py>
line
425 and 452, you might want to look at the kitti_object.py
<https://signal3domain.com/click?redirect=https%3A%2F%2Fgithub.com%2FJRDB-dataset%2Fjrdb_toolkit%2Fblob%2F38f6f32170a601c32a6347eded232fba11307ddb%2Fkitti_object_vis%2Fkitti_object.py%23L1359&dID=1657009437669&linkName=kitti_object.py>
line
1329 and 1359, where the transformation from h, w, l, x, y, z, r (in KITTI
2D camera) to x, y, z, l, h, w, r (in standard 3D LiDAR coordinate) is made.
The transformation from 2D camera to 3D lidar looks like this:
[image: SmartSelect_20220705-181617_Samsung Notes.jpg]
We have updated and added some clarifications to the Github repository.
Please contact us if you have any further confusion, we are always happy to
support.
JRDB team.

**Comment by 20chase** [comment]
Hi @JRDB-dataset  developers, 

Thanks for your helpful reply. We still have some other confusions. 

We may misunderstand the code. In our previous understanding, the `convert_dataset_to_KITTI_tracking.py` is used to convert the `json format label` to `kitti txt format label`. However, as you reply, the `kitti txt format label` that generated `convert_dataset_to_KITTI_tracking.py` seems to be used for KITTI evaluation toolkit and is visualized by `kitti_object.py`. In this way, the ground truth `jrdb txt format label` is not provided in the dataset (only `json format label` is provided, and there are not related code for converting `json format label` to `jrdb txt format label`). So we may suggest the authors adding the `jrdb txt format label` into the `label` directory, which would be more convenient for developers to evaluate their algorithm. 

Moreover, the JRDB paper indicates that `we only evaluate detections on 3D bounding box which encloses more than 10 3D lidar points and lies within 25 meters in bird's eye view`. But in JRDB evaluation toolkit, we don't see any related code for these. Thus, we are wondering If the `jrdb txt format label` file only recorded the objects' information with the 25 meters?

**Comment by JRDB-dataset** [comment]
Hi @20chase,
It's true that we don't provide the JRDB txt format label files, our objective in providing `convert_dataset_to_KITTI_tracking.py` is for those who want to re-use their KITTI code on JRDB dataset. Otherwise, you can use the JSON label files. It's a good suggestion to add `txt format labels` in the `label` directory, we will consider that in future releases.

**Comment by JRDB-dataset** [comment]
@20chase, for the `we only evaluate detections on 3D bounding box which encloses more than 10 3D lidar points and lies within 25 meters in bird's eye view`

Lines 39 and 40 give the constants for these parameters. If you search for them in the rest of the script, you'll find the filtering.
https://github.com/JRDB-dataset/jrdb_toolkit/blob/main/detection_eval/evaluate_object.cpp#L39

**Comment by ldtho** [comment]
Hi @20chase, thank you for the suggestion, please propose a PR, we're happy to review it :)

**Comment by 20chase** [comment]
Hi @ldtho ,

The PR has been proposed. https://github.com/JRDB-dataset/jrdb_toolkit/pull/3#issue-1298827282

**Comment by ldtho** [comment]
Hi @20chase, after discussions with the team, we decided to keep the tracking evaluation code as-is. In tracking, the consistency of the tracks is important, we don't want to have a case where a person that is initially within 25m, then moves out of the 25m range, and come back, to be considered as 2 different track IDs. 
So we understand your concern and appreciate the PR, it would be great to have you working on improving the repo together with us in the future :)
