### ISSUE TITLE
Question: 3d boxes annotation coordinate frame

### ISSUE THREAD

**Issue by kumgleb** [JRDB-dataset/jrdb_toolkit#5]
Hello, thank your for a grate dataset!
I cant find any information about coordinate frame of annotated 3d boxes, are they in a `lidar_upper` or in a `sensor_0` or in some other coordinate frame?

**Comment by deltahue** [comment]
Hi @kumgleb 
I was asking myself the same. I think the answer is in the [File Structure and Label Fromat](https://drive.google.com/file/d/1DyfU_A0x5OzdDGUWPPPWuW-epupIyvT7/view) pdf. 

I think it is alligned with the upper velodyne, but centered around the camera:
![image](https://user-images.githubusercontent.com/61306259/204659776-ff6c1dd7-cf2d-4450-9674-15072da69b82.png)

I would think this is `lidar_upper`, but with the shifted to `camera_rgb_frame`.

**Comment by kumgleb** [comment]
Hi @deltahue 
Thanks for your response, I think you right, annotations are in upper velodine frame, which is aligned with camera axis.
![image](https://user-images.githubusercontent.com/68147941/204718238-8252ee6c-5ae1-4cab-863b-a43bf264bc6c.png)
Besides [File Structure and Label Fromat](https://drive.google.com/file/d/1DyfU_A0x5OzdDGUWPPPWuW-epupIyvT7/view) some additional info can be found in a [blog post](https://blog.vertile.com/article/jackrabbot2/).
